    PROCEDURE SP_UPDATE_PROD(ICOD_PRODUCTO IN VARCHAR,INOM_PRODUCTO IN VARCHAR,ICANTIDAD IN NUMBER,IPRECIO IN NUMBER)
    AS
    BEGIN

    UPDATE PRODUCTO SET CANTIDAD = ICANTIDAD , NOM_PRODUCTO = INOM_PRODUCTO, PRECIO_UNIT = IPRECIO where COD_PRODUCTO = ICOD_PRODUCTO;
   
    END SP_UPDATE_PROD;


    SELECT * FROM ace_sample.producto;
CALL ace_sample.pkg_control.sp_update_prod('222','pancito',1,1)

